// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnKOcNCocor9qiPXx_7zLkRHylOu4VGP0',
    appId: '1:703850334339:web:b8734d46359e13f33ef3b6',
    messagingSenderId: '703850334339',
    projectId: 'chowsa-1bcd9',
    authDomain: 'chowsa-1bcd9.firebaseapp.com',
    storageBucket: 'chowsa-1bcd9.firebasestorage.app',
    measurementId: 'G-1Y8HVX68BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnILlPMEKBZzhGCNm8hKL7larH2TB4Pbs',
    appId: '1:703850334339:android:e6daef272096f8ad3ef3b6',
    messagingSenderId: '703850334339',
    projectId: 'chowsa-1bcd9',
    storageBucket: 'chowsa-1bcd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPwqqDZayyiU_CPYwGM5sUwk7T55oaNMk',
    appId: '1:703850334339:ios:8852a14468dbcb613ef3b6',
    messagingSenderId: '703850334339',
    projectId: 'chowsa-1bcd9',
    storageBucket: 'chowsa-1bcd9.firebasestorage.app',
    iosBundleId: 'za.co.chowsa.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPwqqDZayyiU_CPYwGM5sUwk7T55oaNMk',
    appId: '1:703850334339:ios:8852a14468dbcb613ef3b6',
    messagingSenderId: '703850334339',
    projectId: 'chowsa-1bcd9',
    storageBucket: 'chowsa-1bcd9.firebasestorage.app',
    iosBundleId: 'za.co.chowsa.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnKOcNCocor9qiPXx_7zLkRHylOu4VGP0',
    appId: '1:703850334339:web:a2ac592703a91e983ef3b6',
    messagingSenderId: '703850334339',
    projectId: 'chowsa-1bcd9',
    authDomain: 'chowsa-1bcd9.firebaseapp.com',
    storageBucket: 'chowsa-1bcd9.firebasestorage.app',
    measurementId: 'G-TW5CZYNGQ0',
  );
}
