-- WS6 expansion: more SA staples covering NAMC/PACSA household-basket
-- categories the original 85-row seed missed. Conservative mid-2025 SA
-- retail averages aligned with PnP / Checkers / Shoprite shelf prices.
-- Multi-word entries use specificity=2 so they beat their single-word
-- parents in the keyword-match loop.
--
-- Categories covered:
--   • dairy (full cream / low fat / amasi / cottage / feta / mozz / gouda / cheddar)
--   • proteins (chicken cuts, lamb, pork belly, brisket, biltong, droewors,
--               viennas, russians, bacon, pilchards, snoek, prawns, calamari)
--   • bakery (brown / white / seed loaf / Ouma rusks / burger rolls)
--   • baking (bread flour / self-raising / vanilla / cocoa / coconut / custard)
--   • pantry (basmati / jasmine / brown / Tastic, tinned beans/lentils/chickpeas,
--             tomato paste/puree/chopped, two-minute noodles, masala blends)
--   • condiments (Mrs Ball's, sweet chilli, Worcestershire, soy, vinegars,
--                 atchar, pickles, hummus, sriracha)
--   • produce (sweet potato, butternut, baby marrow, gem squash, leafy greens,
--              frozen veg, naartjie / pawpaw / mango / pineapple / watermelon)
--   • beverages (Rooibos, Five Roses, Ricoffy, Frisco, Milo, Oros, Halls)
--   • household (toilet paper, washing powder, dish liquid, candles, matches)
--
-- All inserts ON CONFLICT (keyword) DO NOTHING so re-applying is safe.

insert into public.price_baselines (keyword, avg_price_zar, category, specificity) values
  ('full cream milk',     24.00, 'dairy',      2),
  ('low fat milk',        23.00, 'dairy',      2),
  ('fat free milk',       22.00, 'dairy',      2),
  ('amasi',               32.00, 'dairy',      2),
  ('greek yoghurt',       45.00, 'dairy',      2),
  ('cottage cheese',      45.00, 'dairy',      2),
  ('cream cheese',        55.00, 'dairy',      2),
  ('feta cheese',         55.00, 'dairy',      2),
  ('mozzarella cheese',   75.00, 'dairy',      2),
  ('cheddar cheese',      95.00, 'dairy',      2),
  ('gouda cheese',        99.00, 'dairy',      2),
  ('condensed milk',      34.00, 'pantry',     2),
  ('evaporated milk',     28.00, 'pantry',     2),
  ('coconut milk',        42.00, 'pantry',     2),
  ('coconut cream',       48.00, 'pantry',     2),
  ('beef mince',          85.00, 'meat',       2),
  ('chicken breasts',     95.00, 'meat',       2),
  ('chicken thighs',      78.00, 'meat',       2),
  ('chicken wings',       65.00, 'meat',       2),
  ('chicken pieces',      75.00, 'meat',       2),
  ('lamb chops',         240.00, 'meat',       2),
  ('pork chops',         110.00, 'meat',       2),
  ('pork belly',         140.00, 'meat',       2),
  ('beef stew',          130.00, 'meat',       2),
  ('beef brisket',       180.00, 'meat',       2),
  ('lamb knuckles',      220.00, 'meat',       2),
  ('biltong',            200.00, 'meat',       2),
  ('droewors',           180.00, 'meat',       2),
  ('vienna sausages',     58.00, 'meat',       2),
  ('russian sausages',    85.00, 'meat',       2),
  ('streaky bacon',       85.00, 'meat',       2),
  ('back bacon',          90.00, 'meat',       2),
  ('lucky star pilchards',32.00, 'meat',       2),
  ('tinned tuna',         30.00, 'pantry',     2),
  ('brown bread',         19.50, 'bakery',     2),
  ('white bread',         18.50, 'bakery',     2),
  ('seed loaf',           28.00, 'bakery',     2),
  ('low gi bread',        30.00, 'bakery',     2),
  ('hot dog rolls',       22.00, 'bakery',     2),
  ('burger rolls',        24.00, 'bakery',     2),
  ('ouma rusks',          65.00, 'bakery',     2),
  ('cake flour',          40.00, 'baking',     2),
  ('bread flour',         45.00, 'baking',     2),
  ('self raising flour',  45.00, 'baking',     2),
  ('white sugar',         35.00, 'pantry',     2),
  ('brown sugar',         38.00, 'pantry',     2),
  ('castor sugar',        35.00, 'baking',     2),
  ('baking soda',         18.00, 'baking',     2),
  ('vanilla essence',     28.00, 'baking',     2),
  ('cocoa powder',        45.00, 'baking',     2),
  ('chocolate chips',     55.00, 'baking',     2),
  ('desiccated coconut',  45.00, 'baking',     2),
  ('custard powder',      32.00, 'baking',     2),
  ('basmati rice',        55.00, 'pantry',     2),
  ('jasmine rice',        52.00, 'pantry',     2),
  ('brown rice',          55.00, 'pantry',     2),
  ('white rice',          45.00, 'pantry',     2),
  ('long grain rice',     48.00, 'pantry',     2),
  ('tastic rice',         55.00, 'pantry',     2),
  ('basmati 2kg',        105.00, 'pantry',     2),
  ('white sugar 2kg',     60.00, 'pantry',     2),
  ('mealie meal 5kg',     85.00, 'pantry',     2),
  ('cake flour 2.5kg',    62.00, 'baking',     2),
  ('baked beans',         24.00, 'pantry',     2),
  ('kidney beans',        28.00, 'pantry',     2),
  ('butter beans',        30.00, 'pantry',     2),
  ('chickpeas',           28.00, 'pantry',     2),
  ('split peas',          30.00, 'pantry',     2),
  ('brown lentils',       32.00, 'pantry',     2),
  ('tomato paste',        14.00, 'pantry',     2),
  ('tomato puree',        18.00, 'pantry',     2),
  ('chopped tomatoes',    18.00, 'pantry',     2),
  ('mrs balls chutney',   55.00, 'condiments', 2),
  ('sweet chilli sauce',  35.00, 'condiments', 2),
  ('peri peri sauce',     38.00, 'condiments', 2),
  ('worcestershire sauce',35.00, 'condiments', 2),
  ('soy sauce',           32.00, 'condiments', 2),
  ('apple cider vinegar', 32.00, 'pantry',     2),
  ('white vinegar',       22.00, 'pantry',     2),
  ('balsamic vinegar',    55.00, 'pantry',     2),
  ('chicken spice',       32.00, 'pantry',     2),
  ('braai spice',         38.00, 'pantry',     2),
  ('curry powder',        32.00, 'pantry',     2),
  ('garam masala',        45.00, 'pantry',     2),
  ('cape malay masala',   48.00, 'pantry',     2),
  ('smoked paprika',      42.00, 'pantry',     2),
  ('ground cumin',        35.00, 'pantry',     2),
  ('ground coriander',    35.00, 'pantry',     2),
  ('ground turmeric',     30.00, 'pantry',     2),
  ('mixed herbs',         28.00, 'pantry',     2),
  ('bay leaves',          22.00, 'pantry',     2),
  ('black pepper',        35.00, 'pantry',     2),
  ('knorrox cubes',       22.00, 'pantry',     2),
  ('chicken stock',       22.00, 'pantry',     2),
  ('beef stock',          22.00, 'pantry',     2),
  ('vegetable stock',     22.00, 'pantry',     2),
  ('two minute noodles',   7.00, 'pantry',     2),
  ('instant noodles',      7.50, 'pantry',     2),
  ('sweet potato',        30.00, 'produce',    2),
  ('baby marrow',         22.00, 'produce',    2),
  ('gem squash',          28.00, 'produce',    2),
  ('butternut squash',    35.00, 'produce',    2),
  ('green beans',         25.00, 'produce',    2),
  ('bell pepper',         18.00, 'produce',    2),
  ('green pepper',        15.00, 'produce',    2),
  ('red pepper',          18.00, 'produce',    2),
  ('spring onion',        14.00, 'produce',    2),
  ('baby spinach',        28.00, 'produce',    2),
  ('mixed lettuce',       30.00, 'produce',    2),
  ('frozen peas',         28.00, 'produce',    2),
  ('frozen mixed veg',    30.00, 'produce',    2),
  ('frozen corn',         28.00, 'produce',    2),
  ('granny smith',        35.00, 'produce',    2),
  ('red apples',          35.00, 'produce',    2),
  ('navel oranges',       35.00, 'produce',    2),
  ('naartjies',           28.00, 'produce',    2),
  ('pineapple',           30.00, 'produce',    2),
  ('mango',               18.00, 'produce',    2),
  ('pawpaw',              40.00, 'produce',    2),
  ('papaya',              40.00, 'produce',    2),
  ('grapes',              40.00, 'produce',    2),
  ('watermelon',          45.00, 'produce',    2),
  ('rooibos tea',         45.00, 'beverages',  2),
  ('five roses',          45.00, 'beverages',  2),
  ('instant coffee',      75.00, 'beverages',  2),
  ('ground coffee',       90.00, 'beverages',  2),
  ('still water',         12.00, 'beverages',  2),
  ('sparkling water',     14.00, 'beverages',  2),
  ('orange juice',        28.00, 'beverages',  2),
  ('apple juice',         28.00, 'beverages',  2),
  ('toilet paper',        55.00, 'household',  2),
  ('dishwashing liquid',  38.00, 'household',  2),
  ('washing powder',      65.00, 'household',  2),
  ('hand soap',           25.00, 'household',  2),
  ('shampoo',             45.00, 'household',  2),
  ('tooth brush',         22.00, 'household',  2),

  -- Single-word additions (specificity=1)
  ('maas',           32.00, 'dairy',     1),
  ('samp',           35.00, 'pantry',    1),
  ('umngqusho',      35.00, 'pantry',    1),
  ('sorghum',        38.00, 'pantry',    1),
  ('semolina',       30.00, 'pantry',    1),
  ('polony',         38.00, 'meat',      1),
  ('vienna',         58.00, 'meat',      1),
  ('frankfurter',    55.00, 'meat',      1),
  ('bacon',          85.00, 'meat',      1),
  ('ham',            78.00, 'meat',      1),
  ('pilchards',      32.00, 'meat',      1),
  ('snoek',         110.00, 'meat',      1),
  ('prawns',        160.00, 'meat',      1),
  ('calamari',       90.00, 'meat',      1),
  ('crayfish',      250.00, 'meat',      1),
  ('chicken livers', 38.00, 'meat',      1),
  ('butternut',      35.00, 'produce',   1),
  ('brinjal',        28.00, 'produce',   1),
  ('eggplant',       28.00, 'produce',   1),
  ('zucchini',       25.00, 'produce',   1),
  ('mushroom',       32.00, 'produce',   1),
  ('mushrooms',      32.00, 'produce',   1),
  ('beetroot',       22.00, 'produce',   1),
  ('kale',           30.00, 'produce',   1),
  ('rocket',         30.00, 'produce',   1),
  ('coriander',      14.00, 'produce',   1),
  ('parsley',        14.00, 'produce',   1),
  ('mint',           15.00, 'produce',   1),
  ('basil',          18.00, 'produce',   1),
  ('thyme',          18.00, 'produce',   1),
  ('rosemary',       18.00, 'produce',   1),
  ('chillies',       18.00, 'produce',   1),
  ('chilli',         18.00, 'produce',   1),
  ('pumpkin',        30.00, 'produce',   1),
  ('mealies',        18.00, 'produce',   1),
  ('corn',           22.00, 'produce',   1),
  ('peas',           28.00, 'produce',   1),
  ('lentils',        32.00, 'pantry',    1),
  ('chickpea',       28.00, 'pantry',    1),
  ('naartjie',       28.00, 'produce',   1),
  ('peach',          28.00, 'produce',   1),
  ('plum',           28.00, 'produce',   1),
  ('strawberries',   45.00, 'produce',   1),
  ('blueberries',    55.00, 'produce',   1),
  ('marmite',        35.00, 'condiments',1),
  ('bovril',         40.00, 'condiments',1),
  ('chutney',        55.00, 'condiments',1),
  ('sriracha',       45.00, 'condiments',1),
  ('hummus',         35.00, 'condiments',1),
  ('relish',         38.00, 'condiments',1),
  ('atchar',         38.00, 'condiments',1),
  ('pickles',        42.00, 'condiments',1),
  ('olives',         38.00, 'condiments',1),
  ('paprika',        42.00, 'pantry',    1),
  ('cumin',          35.00, 'pantry',    1),
  ('turmeric',       30.00, 'pantry',    1),
  ('cinnamon',       32.00, 'pantry',    1),
  ('nutmeg',         35.00, 'pantry',    1),
  ('masala',         45.00, 'pantry',    1),
  ('knorrox',        22.00, 'pantry',    1),
  ('royco',          22.00, 'pantry',    1),
  ('macaroni',       22.00, 'pantry',    1),
  ('lasagne',        28.00, 'pantry',    1),
  ('penne',          22.00, 'pantry',    1),
  ('fusilli',        22.00, 'pantry',    1),
  ('couscous',       35.00, 'pantry',    1),
  ('quinoa',         65.00, 'pantry',    1),
  ('bulgur',         35.00, 'pantry',    1),
  ('milo',           75.00, 'beverages', 1),
  ('horlicks',       75.00, 'beverages', 1),
  ('ovaltine',       75.00, 'beverages', 1),
  ('ricoffy',        55.00, 'beverages', 1),
  ('frisco',         60.00, 'beverages', 1),
  ('oros',           45.00, 'beverages', 1),
  ('halls',          38.00, 'beverages', 1),
  ('cordial',        35.00, 'beverages', 1),
  ('soda',           18.00, 'beverages', 1),
  ('coke',           18.00, 'beverages', 1),
  ('juice',          28.00, 'beverages', 1),
  ('rusks',          65.00, 'snacks',    1),
  ('vetkoek',         8.00, 'snacks',    1),
  ('koeksister',     12.00, 'snacks',    1),
  ('scone',          10.00, 'bakery',    1),
  ('roll',           12.00, 'bakery',    1),
  ('croissant',      14.00, 'bakery',    1),
  ('baguette',       28.00, 'bakery',    1),
  ('detergent',      65.00, 'household', 1),
  ('sponge',         12.00, 'household', 1),
  ('paper towel',    28.00, 'household', 1),
  ('cling wrap',     28.00, 'household', 1),
  ('foil',           35.00, 'household', 1),
  ('matches',        12.00, 'household', 1),
  ('candles',        18.00, 'household', 1)
on conflict (keyword) do nothing;
